channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==2.1.1
  - psutil==5.9.8
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
